# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
