# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='quetion',
            field=models.ManyToManyField(to='forum.Question'),
        ),
    ]
