# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20161119_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quetion',
            new_name='question',
        ),
    ]
