# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20161119_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
