# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20161121_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
