# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20161128_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
